import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const homeStyle : string ="bg-[--bg] text-[--text]";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${homeStyle} `}>
       <div className="w-5/6 m-auto px-14 min-h-screen flex flex-col justify-between">
       <Navbar/>
        {children}
        <Footer/>
       </div>
        </body>
    </html>
  );
}
